services:
  ### Posgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    expose:
      - 3306

  ### MySQL database for Clients
  db-clients:
    container_name: db-clients
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_clients
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3308:3306
    expose:
      - 3306
  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Posgres database for KEYCLOAk
  db-keycloak:
    container_name: db-keycloak
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433



  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command: [ "start-dev" ]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HTTP_PORT: 8181
      KEYCLOAK_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      KEYCLOAK_CORS_ALLOWED_HEADERS: "*"
      KEYCLOAK_CORS_ALLOWED_METHODS: "GET, POST, PUT, DELETE, OPTIONS"


  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1